version: "3"

volumes:
  simple_crm_volume_db:
    
services:
  db:
    image: mysql:latest
    networks:
      - sub-etha
    volumes:
      - simple_crm_volume_db:/data/db
      - ./dbconfig.cnf:/etc/mysql/conf.d/custom.cnf:ro
      - ./dbinit.sql:/data/db/init.sql:ro
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: simplecrm
    command: 
      --default-authentication-plugin=mysql_native_password
      --init-file /data/db/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 50
  simple_crm_api:
    build: api/
    container_name: simple_crm_api
    networks:
      - sub-etha
    restart: always
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - /usr/src/app/api/node_modules
      - ./api/src:/usr/src/app/api/src
    environment: 
      TZ: Europe/Moscow
      NODE_ENV: development
      JWT_ACCESS_SECRET: secret1
      JWT_REFRESH_SECRET: secret2
      SMTP_USER: start.robot@yandex.ru
      SMTP_PASSWORD: Froiji22
      SMTP_SERVICE: yandex
      API_URL: http://localhost:80/api
      CLIENT_URL: http://localhost:80
      MYSQL_DB_ADDR: db
      MYSQL_DB_NAME: simplecrm
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      APP_SERVER_PORT: 80
    healthcheck:
      test: ["CMD", "curl" ,"-sS", "localhost:80"]
      timeout: 5s
      retries: 50
  simple_crm_file_api:
    build: file-api/
    container_name: simple_crm_file_api
    networks:
      - sub-etha
    restart: always
    volumes:
      - /usr/src/app/file-api/node_modules
      - ./file-api/src:/usr/src/app/file-api/src
    environment: 
      TZ: Europe/Moscow
      NODE_ENV: development
      FILE_SERVER_PORT: 80
      CLIENT_URL: http://localhost:80
      JWT_ACCESS_SECRET: secret1
      JWT_REFRESH_SECRET: secret2
    healthcheck:
      test: ["CMD", "curl" ,"-sS", "localhost:80"]
      timeout: 5s
      retries: 50
  simple_crm_dashboard:
    build: dashboard/
    container_name: simple_crm_dashboard
    networks:
      - sub-etha
    restart: always
    depends_on:
      simple_crm_api:
        condition: service_healthy
      simple_crm_file_api:
        condition: service_healthy
    volumes:
      - ./dashboard/src:/usr/src/app/dashboard/src
      - /usr/src/app/dashboard/node_modules
    environment: 
      TZ: Europe/Moscow
      CHOKIDAR_USEPOLLING: 1
      NODE_ENV: development
      VUE_APP_PORT: 80
    healthcheck:
      test: ["CMD", "curl" ,"-sS", "localhost:80"]
      timeout: 5s
      retries: 50
  revproxy:
    build: ./proxy
    image: "reverseproxy:1.0.0"
    depends_on:
      simple_crm_api:
        condition: service_healthy
      simple_crm_dashboard:
        condition: service_healthy
      simple_crm_file_api:
        condition: service_healthy
    networks:
      - sub-etha
    ports:
      - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']
networks:
  sub-etha: